name: hemo1d-fenicsx
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - fenics-dolfinx=0.10.*
  - mpich
  - pyvista
  - numpy
  - scipy
  - matplotlib
  - pytest
  - ruff
  - mypy
  - ipython
  - ipykernel
  - jupyter
  - notebook
  - tqdm